services:
  - type: web
    name: netflix-clone
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm ci && npm run render-build
    startCommand: npm start
    healthCheckPath: /login
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: netflix-clone-redis
          property: connectionString
      - key: TMDB_API_TOKEN
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: TMDB_BASE_URL
        value: https://api.themoviedb.org/3

  - type: redis
    name: netflix-clone-redis
    plan: free
    ipAllowList: []
